//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountRepository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccountEntities : DbContext
    {
        public AccountEntities()
            : base("name=AccountEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Enterprise> Enterprises { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<ResParty> ResParties { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<EntAccount> EntAccounts { get; set; }
        public virtual DbSet<Office> Offices { get; set; }
    }
}
