//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Office()
        {
            this.EntActOffs = new HashSet<EntActOff>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> LocationId { get; set; }
        public int EntId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntActOff> EntActOffs { get; set; }
        public virtual Enterprise Enterprise { get; set; }
        public virtual Location Location { get; set; }
    }
}
